### ISSUE TITLE
[minor] 버튼 텍스트 수정 등 / 수정 검토 요청

### ISSUE THREAD

**Issue by Soarts** [realmani0/seoul_edu#2]
1. 콘텐츠 등록 화면에서 하단 "저장 후 승인 요청" 버튼 텍스트를 "저장"으로 변경

2. 콘텐츠 등록 화면에서 "저장"시 저장 완료 팝업 메시지에 아래의 문구로 변경되었으면 좋겠습니다.
  - [콘텐츠가 저장되었습니다. 저장된 콘텐츠는 [승인 요청 전] 목록에서 확인하세요]

3. [문의] 콘텐츠 관리 화면으로 이동시 디폴트로 [게시됨] 목록이 보여지도록 했는데,
   콘텐츠 관리 화면 접근시 [승인 요청 전]에 해당하는 건이 있는지 체크하고 1건이라도 있는 경우 [승인 요청 전] 화면을 디폴트로 표시하는 로직이 추가 가능한지요?

4. 콘텐츠 등록 시 파일 확장명이 대문자이면 같은 확장자여도 등록되지 않는 현상 있음.

**Comment by realmani0** [comment]
1. 처리완료
2. 처리완료
3. 가능은 할것 같으나..로직이 복잡하며 시간이 많이 걸릴것 같음. 
    현 일정에 대한 문제가 있음
4. 처리완료
- 
테스트가 필요합니다.

**Comment by Soarts** [comment]
테스트 완료, 이슈 닫겠습니다.
3번  항목에 대해서는 차후 이슈가 될 때 다시 논의드리거나 하겠습니다
