### ISSUE TITLE
[2.6] 테스트 결과

### ISSUE THREAD

**Issue by Soarts** [realmani0/seoul_edu#3]
[테스트 범위]
1. 관리자 - 사용자 관리(생성 / 중지), 콘텐츠 관리(승인,반려,게시중지,게시, 삭제, 수정), 카테고리 관리(생성)
2. 사용자 - 콘텐츠 관리(등록, 승인요청, 수정, 삭제)

[공통]
1. 콘텐츠 관리 메뉴에서 특정 콘텐츠에 대하여 수정화면에 진입했다가 수정하거나 취소한 경우 해당하는 분류의 관리화면으로 돌아가게 했으면 함. (ex. '반려됨' 화면에서 콘텐츠 하나를 수정하고 다시 돌아왔을 때 '반려됨' 화면이 보이도록._) (현재는 항상 '게시됨'이 디폴트임)
2. png 썸네일도 등록할 수는 없는지.(현재는 jpg만 지원됨.

[관리자]
1. 사용자가 등록한 콘텐츠 삭제 안됨.
2. [게시됨] 사용자가 등록한 콘텐츠 수정 안됨.
3. [반려됨] 사용자가 등록한 콘텐츠 수정 안됨.
4. [게시중지] 수정 화면에서 하단 버튼 오타(개시 -> 게시)
5. 상단 메뉴 탭 오타 수정(관리자 관리 -> 사용자 관리)

[사용자]
1. 자신이 등록한 콘텐츠중 [게시됨]이나 [승인 대기] 상태의 콘텐츠인 경우는 삭제할 수 없어야 함.

**Comment by realmani0** [comment]
수정결과

[공통]
1.콘텐츠 관리 메뉴에서 특정 콘텐츠에 대하여 수정화면에 진입했다가 수정하거나 취소한 경우 해당하는 분류의 관리화면으로 돌아가게 했으면 함. (ex. '반려됨' 화면에서 콘텐츠 하나를 수정하고 다시 돌아왔을 때 '반려됨' 화면이 보이도록._) (현재는 항상 '게시됨'이 디폴트임)
2.png 썸네일도 등록할 수는 없는지.(현재는 jpg만 지원됨.
- 추후....

[관리자]
1.사용자가 등록한 콘텐츠 삭제 안됨.
- 삭제 잘되는것 같음

2.[게시됨] 사용자가 등록한 콘텐츠 수정 안됨.
- 수정완료

3.[반려됨] 사용자가 등록한 콘텐츠 수정 안됨.
- 수정완료

4.[게시중지] 수정 화면에서 하단 버튼 오타(개시 -> 게시)
- 수정완료

5.상단 메뉴 탭 오타 수정(관리자 관리 -> 사용자 관리)
- 처리완료

[사용자]
1.자신이 등록한 콘텐츠중 [게시됨]이나 [승인 대기] 상태의 콘텐츠인 경우는 삭제할 수 없어야 함.
- 처리완료(삭제아이콘 제거)
