### ISSUE TITLE
[2.21] 실서버 테스트

### ISSUE THREAD

**Issue by Soarts** [realmani0/seoul_edu#4]
1. 슈퍼관리자에서 관리자 등록시 등록 버튼 동작하지 않음.

2. 내서재에서 사용자로 접속시 등록된 책이 보여지지 않음.(동일 관리자 내에서 등록한 책은 전부 보여져야 함.)

**Comment by realmani0** [comment]
1. 처리완료
2. 완료 - 테스트 해봐야함.
